// Package api hosts the generated Hostinger API client.
//
// The client is generated by oapi-codegen from the OpenAPI spec at the repo root.
// Run `go generate ./...` after updating api.json to regenerate.
package api

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen -config cfg.yaml ../../api.json
